import Head from "next/head";
import Image from "next/image";
import { Nunito } from "next/font/google";
import About from "@/Components/About";
import Cover from "@/Components/Cover";
import Banner from "@/Components/Banner";
import Goal from "@/Components/Goal";
import MealPlanSection from "@/Components/MealPlanSection";
import Footer from "@/Components/Footer";
import NavBar from "@/Components/NavBar";

const nunito = Nunito({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Meal Planner Helper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.fontshare.com/v2/css?f[]=boska@900,500,400,200,700,300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Cover></Cover>
        <About></About>
        <Banner></Banner>
        <Goal></Goal>
        <MealPlanSection></MealPlanSection>
      </main>
    </>
  );
}
